### ISSUE TITLE
New neuron available for sony monitor (and android tv) 

### ISSUE THREAD

**Issue by Riseryn** [kalliope-project/kalliope-project.github.io#24]
Hi,
I have made a neuron to control Sony Bravia Pro monitor;
It should also works with Sony Bravia Android TV.
You can check it at https://github.com/Riseryn/sony_commandl

**Comment by Sispheor** [comment]
Thanks, I'll add it to the website when I have time.

**Comment by Sispheor** [comment]
Done

**Comment by Riseryn** [comment]
Thanks
